## **Loading The Data Set**

In [115]:
import pandas as pd

df = pd.read_csv("DataSet/teams.csv")

teams = df[["team", "country", "year", "athletes", "age", "height", "weight", "prev_medals", "medals"]]

teams

,team,country,year,athletes,age,height,weight,prev_medals,medals
0,AFG,Afghanistan,1964,8,22.0,161.0,64.2,0.0,0
1,AFG,Afghanistan,1968,5,23.2,170.2,70.0,0.0,0
2,AFG,Afghanistan,1972,8,29.0,168.3,63.8,0.0,0
3,AFG,Afghanistan,1980,11,23.6,168.4,63.2,0.0,0
4,AFG,Afghanistan,2004,5,18.6,170.8,64.8,0.0,0
...,...,...,...,...,...,...,...,...,...
2139,ZIM,Zimbabwe,2000,26,25.0,179.0,71.1,0.0,0
2140,ZIM,Zimbabwe,2004,14,25.1,177.8,70.5,0.0,3
2141,ZIM,Zimbabwe,2008,16,26.1,171.9,63.7,3.0,4
2142,ZIM,Zimbabwe,2012,9,27.3,174.4,65.2,4.0,0
2143,ZIM,Zimbabwe,2016,31,27.5,167.8,62.2,0.0,0

## **Checking for Correlation**

In [116]:
teams.select_dtypes(include=['number']).corr()["medals"]

year          -0.021603
athletes       0.840817
age            0.025096
height         0.141055
weight         0.090577
prev_medals    0.920048
medals         1.000000
Name: medals, dtype: float64

## **Visualize Correlation**

In [117]:
import seaborn as sns

Correlation between athletes and medals

In [118]:
sns.lmplot(x="athletes", y="medals", data=teams, fit_reg=True, ci=None)

Correlation between age and medals

In [119]:
sns.lmplot(x="age", y="medals", data=teams, fit_reg=True, ci=None)

Correlation between height and medals

In [120]:
sns.lmplot(x="height", y="medals", data=teams, fit_reg=True, ci=None)

Correlation between weight and medals

In [121]:
sns.lmplot(x="weight", y="medals", data=teams, fit_reg=True, ci=None)

In [122]:
teams.plot.hist(y="medals")

## **Cleaning Data**

Check for missing data

In [123]:
teams[teams.isnull().any(axis=1)]

,team,country,year,athletes,age,height,weight,prev_medals,medals
19,ALB,Albania,1992,9,25.3,163.0,75.2,NaN,0
26,ALG,Algeria,1964,7,26.0,175.0,65.0,NaN,0
39,AND,Andorra,1976,3,28.3,174.7,78.0,NaN,0
50,ANG,Angola,1980,17,17.4,171.7,62.5,NaN,0
59,ANT,Antigua and Barbuda,1976,17,23.2,178.6,71.6,NaN,0
...,...,...,...,...,...,...,...,...,...
2092,VIN,Saint Vincent and the Grenadines,1988,6,20.5,157.0,57.0,NaN,0
2103,YAR,North Yemen,1984,3,27.7,163.3,57.7,NaN,0
2105,YEM,Yemen,1992,8,19.6,169.0,60.0,NaN,0
2112,YMD,South Yemen,1988,5,23.6,175.0,63.3,NaN,0
2120,ZAM,Zambia,1964,15,21.7,175.7,68.0,NaN,0

Drop Missing Data

In [124]:
teams=teams.dropna()

teams

,team,country,year,athletes,age,height,weight,prev_medals,medals
0,AFG,Afghanistan,1964,8,22.0,161.0,64.2,0.0,0
1,AFG,Afghanistan,1968,5,23.2,170.2,70.0,0.0,0
2,AFG,Afghanistan,1972,8,29.0,168.3,63.8,0.0,0
3,AFG,Afghanistan,1980,11,23.6,168.4,63.2,0.0,0
4,AFG,Afghanistan,2004,5,18.6,170.8,64.8,0.0,0
...,...,...,...,...,...,...,...,...,...
2139,ZIM,Zimbabwe,2000,26,25.0,179.0,71.1,0.0,0
2140,ZIM,Zimbabwe,2004,14,25.1,177.8,70.5,0.0,3
2141,ZIM,Zimbabwe,2008,16,26.1,171.9,63.7,3.0,4
2142,ZIM,Zimbabwe,2012,9,27.3,174.4,65.2,4.0,0
2143,ZIM,Zimbabwe,2016,31,27.5,167.8,62.2,0.0,0

## **Making The Model**

Split Data

In [125]:
train = teams[teams["year"] < 2012].copy()

test = teams[teams["year"] >= 2012].copy()

Check rows and columns of training and test sets

In [126]:
train.shape

(1609, 9)

In [127]:
test.shape

(405, 9)

## **Training The Model**

In [128]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression() # This is the trained model

Creating Predictors

In [129]:
predictors = ["athletes", "age", "height", "weight", "prev_medals"]

Create Target

In [130]:
target = "medals"

## **Fit the model**

In [131]:
reg.fit(train[predictors], train["medals"])

LinearRegression()

## **Making Predictions**

In [132]:
predictions = reg.predict(test[predictors])

predictions

array([-1.02885496e+00, -1.07072549e+00, -1.44215653e+00, -1.83323021e+00,
        2.07335457e+00,  3.95195516e+00, -2.24549632e+00, -1.87997477e+00,
        2.32555445e-01, -4.31175393e-01, -1.78779083e+00, -1.44913187e+00,
        4.64138349e+01,  2.84485977e+01,  4.69034694e+00,  2.87464060e+00,
       -1.35772244e+00, -1.63479751e+00, -1.26353470e+00, -1.94730155e+00,
        1.46384834e+02,  1.20365241e+02,  6.16175029e+00,  3.60681047e+00,
        7.50462535e+00,  1.02061851e+01,  4.92091310e+00,  3.31388062e+00,
       -9.42241338e-01, -1.05025159e+00, -1.93681651e+00, -1.53595987e+00,
       -1.51526617e+00, -1.51284036e+00,  1.14226826e+01,  9.81875057e+00,
       -2.03243748e+00, -1.97033255e+00, -2.00803277e+00, -1.62138993e+00,
       -1.26621522e+00, -1.74111966e+00, -2.29090311e+00, -1.42312536e+00,
       -1.57972440e+00, -2.50033119e+00,  3.26615268e+01,  2.50330503e+01,
       -1.67085076e+00, -1.30654809e+00, -2.18081994e+00, -5.70855682e-01,
        7.81097519e+01,  8.38802798e+01, -8.61198665e-01,  1.05393021e+00,
       -1.36934589e+00, -1.11014839e+00,  6.74040526e+00,  3.42969766e+00,
       -1.70910281e+00, -1.74142097e+00, -1.63624730e+00, -1.38381983e+00,
       -1.48617196e+00, -1.70855671e+00,  4.94323279e+01,  6.81386985e+01,
       -2.01874796e+00, -1.92356062e+00, -1.66439024e+00, -1.22533168e+00,
       -1.38112014e+00, -2.25551261e+00,  1.47992263e+00,  1.08156429e+00,
        1.70375221e+02,  1.27547481e+02, -1.37934345e+00, -1.28548607e+00,
        1.27442099e+00, -6.37420638e-01, -1.60137266e+00, -1.42045818e+00,
       -5.13671690e-01, -1.24915048e+00,  8.06107586e+00,  1.52301100e+01,
       -1.56031001e+00, -1.51890983e+00, -1.75056650e+00, -1.99156455e+00,
       -1.60574108e+00, -1.47865905e+00,  9.61728806e+00,  3.02543061e+01,
        4.16484295e+01,  1.86944790e+01, -1.45255002e+00, -1.42809129e-02,
        1.41727497e+01,  1.76471137e+01,  2.23993870e+01,  1.97233310e+01,
       -1.63439395e+00, -1.64068930e+00, -1.95327095e+00, -2.23662625e+00,
        1.80181533e+00,  1.40179421e+00,  1.26745484e+00,  6.79247916e-01,
        8.21228129e+00,  9.17708859e+00, -1.47583981e+00, -1.56495666e+00,
       -1.07130908e+00, -9.77699236e-01,  7.45527203e+01,  7.09390778e+01,
        2.29444491e+00,  2.49481954e+00,  5.48617968e+00,  5.87133832e+00,
       -1.40233906e+00,  1.67002412e+00,  6.29995090e+00,  6.19485200e+00,
        8.59947714e+01,  9.59084813e+01, -1.52381080e+00, -6.71193331e-01,
       -3.20538475e-01, -9.86710083e-01, -7.54772046e-01,  1.07638493e+02,
        1.26563476e+02, -1.63972969e+00, -1.69650345e+00,  4.87617889e+00,
        6.30625665e+00, -2.13033680e+00, -2.14710169e+00,  1.08547799e+02,
        1.06680862e+02, -1.37280914e+00, -8.24777073e-01,  1.10580832e+01,
        7.21358003e+00, -1.91735983e+00, -7.88678678e-01, -2.48007521e-01,
        4.78511801e-01, -1.20860814e+00, -1.08200236e+00, -1.30071234e+00,
       -1.83756336e+00, -1.59987204e+00, -9.24913360e-01, -1.85558822e+00,
       -1.58436525e+00,  1.98429617e+00,  2.02029866e+00,  1.19254402e-01,
       -5.18243276e-01,  3.22582789e+01,  3.16938841e+01,  5.19922030e+00,
        1.86666381e+00,  6.90240930e+00,  1.17821285e+01, -2.13518079e+00,
       -2.01085120e+00,  3.48044856e+00,  1.13522844e+01,  5.16572561e+00,
        7.93352262e+00, -1.10118456e+00, -7.14796820e-01,  1.04299561e+01,
       -1.19251234e+00,  2.62065526e+00,  1.99591286e+00, -1.67120817e+00,
       -2.13174991e+00,  5.65936483e+01,  7.73061739e+01, -1.80245707e+00,
       -1.27973949e+00,  1.26215902e+01,  2.20905480e+01, -1.49810675e+00,
       -1.48324931e+00,  6.50115905e+01,  9.23906515e+01,  1.69451637e+01,
        1.63918548e+01,  1.28091728e+01,  1.18375685e+01,  5.83867752e-01,
       -5.56890463e-01, -9.80718361e-01, -1.09239156e+00,  7.88184979e+01,
        6.25565018e+01, -7.82315677e-01,  1.63935730e+00, -1.79526007e+00,
       -1.23741776e+00, -1.47767305e+00,  3.33895528e+00,  2.11352145e+00,
       -1.97842113e+00, -1.78302081e+00, -2.11585958e+00, -1.94731000e+00,
       -1.84759926e+00, -1.54358748e+00, -1.76599325e+00, -1.30228049e+00,
       -1.50344267e+00, -1.95687408e+00, -2.06932414e+00,  6.42527126e+00,
        6.90814567e+00, -1.80876903e+00, -1.54119061e+00, -1.40490269e+00,
       -1.65557000e+00,  4.00928706e+00,  2.14053837e+00,  1.68360569e+00,
        2.62643857e+00, -1.61167906e+00, -1.19545792e+00, -1.29030893e-03,
        9.02296460e-01, -1.17436703e+00, -1.01305659e+00,  9.48437915e+00,
        2.58337686e+01,  3.21430567e+00,  5.04003204e+00, -1.43433849e+00,
       -8.98552797e-01, -1.73521986e+00, -1.47373916e+00, -1.83061638e+00,
       -1.95696663e+00, -1.69994752e+00, -1.42470912e+00, -1.41715553e-01,
        1.04511027e+01, -2.32828063e+00, -1.90344166e+00, -1.52305993e+00,
       -1.55883915e+00, -5.56334356e-01, -1.33697079e+00, -1.56416391e+00,
       -2.13064903e+00, -1.62254844e+00, -1.69930892e+00, -1.70503371e+00,
       -1.89596760e+00, -1.85154168e+00, -1.55543033e+00,  5.91720295e+01,
        7.29722643e+01, -1.05838482e+00, -1.06778065e+00,  1.90441530e+01,
        3.26028752e+00, -1.68363561e+00, -1.73808568e+00,  1.88272851e+01,
        1.57282509e+01, -1.31068152e+00, -1.25688104e+00,  2.35286320e+01,
        3.46262476e+01, -1.57357243e+00, -1.81286942e+00, -6.56472328e-01,
       -1.25527868e+00, -8.62958238e-01, -9.31040277e-01, -1.58577972e+00,
       -1.64997765e+00, -8.21617933e-01,  3.94519162e-01, -1.03373295e+00,
       -8.44298491e-01, -1.54173738e+00, -1.99640581e+00, -1.14118270e+00,
       -1.00193334e+00, -1.29752458e+00, -1.63260196e+00,  3.09340064e+01,
        2.72258483e+01,  6.19495772e+00,  6.63752484e+00,  7.08305604e+00,
        5.61095826e+00, -2.46159604e-01,  1.94717467e+00, -9.00862446e-01,
        1.87630024e+00,  2.55388617e+01,  1.82781862e+01,  8.83860671e+00,
        1.55776387e+01,  1.43698055e+02,  1.31952485e+02, -1.31997929e+00,
       -1.36883078e+00, -1.69249574e+00, -1.19951156e+00, -1.45440693e-01,
       -1.05485814e+00, -1.25460929e+00, -1.57225147e+00,  3.10358769e+00,
        3.34663368e+00, -1.41518373e+00, -1.94480994e+00, -2.37472855e+00,
       -8.20763365e-01,  7.00249432e+00,  6.30411088e+00, -1.75081822e+00,
       -2.47697577e+00, -1.88131409e+00, -1.64260600e+00,  1.81648044e+01,
        1.84188825e+01, -1.55565967e+00, -1.53500026e+00, -1.96576981e+00,
       -2.02786380e+00, -1.16758976e+00, -1.49059002e+00,  1.48140973e+01,
        1.16411605e+01, -1.34001616e+00, -2.12507168e+00,  9.64606243e+00,
        5.60471092e+00,  1.47300111e+01,  2.73637628e+01, -1.79294955e+00,
       -2.12824007e+00, -1.55547047e+00, -1.95806657e+00, -1.64563124e+00,
       -1.38364014e+00, -2.06901807e+00, -1.49105428e+00,  4.17689692e+00,
        4.37484136e+00,  4.08025416e-01, -9.91686990e-01, -1.32685738e+00,
       -1.22980981e+00, -1.43939238e+00, -1.43302434e+00, -8.85046106e-01,
       -7.56591483e-01,  5.07698160e+00,  4.34911525e+00,  4.99663227e+00,
        8.28175883e+00,  4.49196324e+00,  4.41190614e+00,  1.15945600e+01,
        1.00530990e+01, -8.40794494e-01, -2.58358031e+00, -2.04959822e-01,
       -1.29149361e+00, -9.86330956e-01,  3.59402424e-01,  4.28919510e+01,
        3.67477170e+01, -3.70217962e-01, -1.36791567e+00,  2.85074817e+02,
        2.35471288e+02,  6.35463053e+00,  5.82744152e+00, -1.58862487e+00,
       -1.88930640e+00,  4.71116217e+00,  5.86694043e+00,  6.84810925e-01,
       -9.16808367e-02, -2.04983083e+00, -1.88249419e+00, -1.47381298e+00,
       -1.36954002e+00, -1.52883660e+00, -1.72286736e+00,  1.19023211e+00,
        9.31111531e-02])

**re-scale predictions to make it more readable and clearer**

Assign predictions to a column in our test dataframe

In [133]:
test["predictions"] = predictions

test

,team,country,year,athletes,age,height,weight,prev_medals,medals,predictions
6,AFG,Afghanistan,2012,6,24.8,171.7,60.8,1.0,1,-1.028855
7,AFG,Afghanistan,2016,3,24.7,173.7,74.0,1.0,0,-1.070725
24,ALB,Albania,2012,10,25.7,176.8,80.2,0.0,0,-1.442157
25,ALB,Albania,2016,6,23.7,176.2,67.2,0.0,0,-1.833230
37,ALG,Algeria,2012,39,24.8,174.3,66.9,2.0,1,2.073355
...,...,...,...,...,...,...,...,...,...,...
2111,YEM,Yemen,2016,3,19.3,169.7,65.7,0.0,0,-1.369540
2131,ZAM,Zambia,2012,7,22.6,176.2,74.2,0.0,0,-1.528837
2132,ZAM,Zambia,2016,7,24.1,175.2,67.5,0.0,0,-1.722867
2142,ZIM,Zimbabwe,2012,9,27.3,174.4,65.2,4.0,0,1.190232
2143,ZIM,Zimbabwe,2016,31,27.5,167.8,62.2,0.0,0,0.093111

Replace prediction value <0 to 0 (remove neagtives)

In [134]:
test.loc[test["predictions"] < 0, "predictions"] = 0

Round up the data

In [135]:
test["predictions"] = test["predictions"].round()

In [136]:
test

,team,country,year,athletes,age,height,weight,prev_medals,medals,predictions
6,AFG,Afghanistan,2012,6,24.8,171.7,60.8,1.0,1,0.0
7,AFG,Afghanistan,2016,3,24.7,173.7,74.0,1.0,0,0.0
24,ALB,Albania,2012,10,25.7,176.8,80.2,0.0,0,0.0
25,ALB,Albania,2016,6,23.7,176.2,67.2,0.0,0,0.0
37,ALG,Algeria,2012,39,24.8,174.3,66.9,2.0,1,2.0
...,...,...,...,...,...,...,...,...,...,...
2111,YEM,Yemen,2016,3,19.3,169.7,65.7,0.0,0,0.0
2131,ZAM,Zambia,2012,7,22.6,176.2,74.2,0.0,0,0.0
2132,ZAM,Zambia,2016,7,24.1,175.2,67.5,0.0,0,0.0
2142,ZIM,Zimbabwe,2012,9,27.3,174.4,65.2,4.0,0,1.0
2143,ZIM,Zimbabwe,2016,31,27.5,167.8,62.2,0.0,0,0.0

**Check for mean absolute error**

In [137]:
from sklearn.metrics import mean_absolute_error

error = mean_absolute_error(test["medals"], test["predictions"])

In [138]:
error

3.254320987654321

Check if our mean prediction error is a good or bad error

In [139]:
teams.describe()["medals"]

count    2014.000000
mean       10.990070
std        33.627528
min         0.000000
25%         0.000000
50%         0.000000
75%         5.000000
max       442.000000
Name: medals, dtype: float64

**Look team by team to see how our predictions look**

In [140]:
test[test["team"] == "USA"]

,team,country,year,athletes,age,height,weight,prev_medals,medals,predictions
2053,USA,United States,2012,689,26.7,178.3,74.7,317.0,248,285.0
2054,USA,United States,2016,719,26.4,178.0,73.8,248.0,264,235.0

In [141]:
test[test["team"] == "IND"]

,team,country,year,athletes,age,height,weight,prev_medals,medals,predictions
907,IND,India,2012,95,26.0,174.2,72.7,3.0,6,7.0
908,IND,India,2016,130,26.1,170.0,66.3,6.0,2,12.0

## **Check error by country**

In [142]:
errors = (test["medals"] - test["predictions"]).abs()

errors

6       1.0
7       0.0
24      0.0
25      0.0
37      1.0
       ...
2111    0.0
2131    0.0
2132    0.0
2142    1.0
2143    0.0
Length: 405, dtype: float64

Group by team

In [143]:
error_by_team  = errors.groupby(test["team"]).mean()

error_by_team

team
AFG    0.5
ALB    0.0
ALG    1.5
AND    0.0
ANG    0.0
      ...
VIE    1.5
VIN    0.0
YEM    0.0
ZAM    0.0
ZIM    0.5
Length: 204, dtype: float64

Check how many medals each country earned on average

In [144]:
medals_by_team = test["medals"].groupby(test["team"]).mean()

Find the ratio between our errors

In [145]:
error_ratio = error_by_team / medals_by_team

error_ratio

team
AFG    1.0
ALB    NaN
ALG    1.0
AND    NaN
ANG    NaN
      ...
VIE    1.5
VIN    NaN
YEM    NaN
ZAM    NaN
ZIM    inf
Length: 204, dtype: float64

Take only values that are not missing from the error ratio remove NaN

In [146]:
error_ratio[~pd.isnull(error_ratio)]

team
AFG    1.000000
ALG    1.000000
ARG    0.804878
ARM    0.428571
AUS    0.357143
         ...
USA    0.128906
UZB    0.625000
VEN    1.750000
VIE    1.500000
ZIM         inf
Length: 103, dtype: float64

Clean up infinite values

In [147]:
import numpy as np
error_ratio = error_ratio[np.isfinite(error_ratio)]

In [148]:
error_ratio

team
AFG    1.000000
ALG    1.000000
ARG    0.804878
ARM    0.428571
AUS    0.357143
         ...
UKR    0.951220
USA    0.128906
UZB    0.625000
VEN    1.750000
VIE    1.500000
Length: 97, dtype: float64

Create a histogram for the error ratio

In [149]:
error_ratio.plot.hist()

**Check which country tends to get a lot of medal from the olympics**

For example our error is very low for countries who tend to send more athletes to the olympics

In [150]:
error_ratio.sort_values()

team
DOM    0.000000
FRA    0.022472
CAN    0.056452
NZL    0.063492
RUS    0.082353
         ...
MAR    2.000000
EGY    2.400000
HKG    3.000000
POR    3.333333
AUT    4.000000
Length: 97, dtype: float64

## **Save Our Model**

In [151]:
import joblib 

joblib.dump(reg, "Summer.Olympics_Medal_Prediction_V1")

['Summer.Olympics_Medal_Prediction_V1']